output "log_summary" {
  description = "Summary of log generation configuration"
  value = {
    total_iterations     = var.log_iterations
    message_size        = var.log_message_size
    estimated_log_size  = "${(var.log_iterations * var.log_message_size) / 1024 / 1024} MB (from variables)"
    total_resources     = var.resource_count_tier1 + var.resource_count_tier2 + var.resource_count_tier3 + var.resource_count_tier4
    additional_logs     = "Generated by ${var.resource_count_tier1 + var.resource_count_tier2 + var.resource_count_tier3 + var.resource_count_tier4} null_resource instances"
    timestamp          = timestamp()
    execution_id       = md5(timestamp())
  }
}

output "detailed_logs" {
  description = "Detailed log entries for verbose output"
  value = [
    for i in range(100) : {
      entry_id   = i
      timestamp  = timestamp()
      message    = "Detailed log entry ${i} with extensive information about the Terraform execution. This output is designed to contribute to the overall log file size by including verbose details about each resource, its configuration, and execution status. Additional padding: ${join("", [for j in range(10) : "PADDING_${j}_"])}"
      metadata   = {
        instance = i
        random   = md5("${i}-${timestamp()}")
        status   = "completed"
      }
    }
  ]
}

output "verbose_execution_log" {
  description = "Verbose execution log with multiple entries"
  value = join("\n", [
    for i in range(500) : format(
      "[%05d] Execution log entry at %s - Resource provisioning details, configuration parameters, and system state information. This entry contains verbose debugging output to assist with troubleshooting and monitoring. Additional context: %s",
      i,
      timestamp(),
      md5("${i}-${timestamp()}")
    )
  ])
}

output "resource_statistics" {
  description = "Statistics about resource creation"
  value = {
    tier1_resources = var.resource_count_tier1
    tier2_resources = var.resource_count_tier2
    tier3_resources = var.resource_count_tier3
    tier4_resources = var.resource_count_tier4
    total_resources = var.resource_count_tier1 + var.resource_count_tier2 + var.resource_count_tier3 + var.resource_count_tier4
    iterations_per_resource = var.iterations_per_resource
    estimated_total_iterations = (var.resource_count_tier1 + var.resource_count_tier2 + var.resource_count_tier3 + var.resource_count_tier4) * var.iterations_per_resource
  }
}

output "execution_metadata" {
  description = "Metadata about the execution"
  value = {
    terraform_version = ">=1.0"
    execution_time    = timestamp()
    workspace_info    = "IBM Cloud Schematics Large Log Generator"
    purpose          = "Generate 100MB+ log files for testing"
    log_generators   = ["tier1", "tier2", "tier3", "tier4"]
  }
}
